---
layout: post
title: "Crashlytis 上的棘手异常"
description: ""
category: 
tags: [ios ]
---
{% include JB/setup %}

# 问题背景

经过一段时间的系统重构和crash处理，app上存在的问题也越来越少了。但是在crash列表上有几个问题，跟一般crash很不同，很难定位问题。

# 问题描诉

下面就是那个Crash的崩溃栈

```
Thread : Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x3337fdfc __pthread_kill + 8
1  libsystem_pthread.dylib        0x333fdd37 pthread_kill + 62
2  libsystem_c.dylib              0x3331f909 abort + 76
3  libc++abi.dylib                0x3265b9c9 __cxa_bad_cast
4  libc++abi.dylib                0x32675671 default_unexpected_handler()
5  libobjc.A.dylib                0x32d39f25 _objc_terminate() + 192
6  libc++abi.dylib                0x32672de3 std::__terminate(void (*)()) + 78
7  libc++abi.dylib                0x326728af __cxa_rethrow + 102
8  libobjc.A.dylib                0x32d39dd3 objc_exception_rethrow + 42
9  CoreFoundation                 0x2559e6bd CFRunLoopRunSpecific + 632
10 CoreFoundation                 0x2559e433 CFRunLoopRunInMode + 106
11 GraphicsServices               0x2c94c0a9 GSEventRunModal + 136
12 UIKit                          0x28b88809 UIApplicationMain + 1440
13 Spec                           0x0010de17 main (main.m:16)
```

跟调试时不打开全局异常断点时的异常栈一样。

# 别人怎么说

StackOverFlow上真是什么人都有，比如说[这个](http://stackoverflow.com/questions/13777446/ios-how-to-get-stack-trace-of-an-unhandled-stdexception)。 简单的说，就是oc对异常的处理分为两种，OC的和C++的。正常情况下，我们都能拿到相关的异常栈，但如果是C++的异常出现时，OC会调用**标准**异常处理方法。然后再次发出oc异常。这样的处理，就会把原有的保存的C++异常栈给破坏了。所以给我们看到的崩溃栈，就没有什么有价值的信息了。

# 怎么办

还是往StackOverFlow上先找找，又让我找到了[这个](http://stackoverflow.com/questions/8100054/no-exception-stack-trace-in-console-under-xcode-4-2-ios-5)。我再想，既然是因为Runloop的默认异常处理方法导致的异常栈丢失，那么如果我能在第二次发出异常之前捕捉异常并记录下来，不就可以解决这个问题了。

Crashlytis准备了这个[工具](http://support.crashlytics.com/knowledgebase/articles/92519-how-do-i-use-logging) ，可以在他们的Crash列表上看到想要记录的信息。

于是我仿照上面的方法，对main.m做了这样的处理。

```
#import <Crashlytics/Crashlytics.h>

int main(int argc, char *argv[])
{
    NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];
    int retVal = -1;
    @try {
        retVal = UIApplicationMain(argc, argv, nil, NSStringFromClass([VSAppDelegate class]));
    }
    @catch (NSException* exception) {
        CLSNSLog(@"Uncaught exception: %@", exception.description);
        CLSNSLog(@"Stack trace: %@", [exception callStackSymbols]);
    }
    [pool release];
    return retVal;
}
```

等待新版本上线后给出验证。

# 总结

从最近的iOS 8 的相关实践看来，apple的sdk代码质量在下降，各种比较明显的问题都被碰到过了。虽然还可以说这个默认异常处理的机制，是一次从OSX移植后所遗留的问题，但一直没怎么改动，也可以看出apple的QC不是很关注。 
希望apple不要变成下一个ms！